name: do_an_application
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  equatable: ^2.0.7
  app_settings: ^5.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  dio_log_sds:
    git:
      url: https://git-sds.softdreams.vn:7990/scm/sma/dio_log_sds.git
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  bot_toast: ^4.1.3
  pull_to_refresh: ^2.0.0
  screenshot: ^3.0.0
  fluttertoast: ^8.2.2
  share_plus: 10.0.2
  flutter_holo_date_picker: ^2.0.0
  screenshot_callback:
    git:
      url: https://github.com/pvc97/flutter_screenshot_callback.git
  upgrader: 10.3.0
  local_auth_android: ^1.0.47
  local_auth: ^2.1.0
  loading_overlay_pro: ^2.1.1
  flutter_animator: ^3.1.1
  flutter_inappwebview: 6.1.5
  logger: ^2.0.2+1
  open_file_plus: ^3.4.1+1
  permission_handler: ^11.3.1
  tiengviet: ^1.0.0
  flutter_multi_formatter: ^2.10.2
  sds_share_pdf:
    git:
      url: https://github.com/pvc97/sds_share_pdf.git
  keyboard_actions: ^4.2.0
  flutter_rounded_date_picker: ^3.0.4
  shimmer: ^3.0.0
  dotted_border: ^2.1.0
  scroll_datetime_picker: ^0.2.2
  table_calendar: ^3.1.3
  flutter_picker_plus: 1.5.0
  location: ^7.0.0
  device_info_plus: ^10.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    # assets start

    # GENERATED CODE - DO NOT MODIFY MANUALLY
    # **************************************************************************
    # Auto generated by SoftDreams Developer
    # **************************************************************************

    - assets/fonts/
    - assets/icons/
    - assets/images/

  # assets end
